### ISSUE TITLE
How to add integrated laptop cam

### ISSUE THREAD

**Issue by OscarCreator** [paukstelis/octoprint_deploy#167]
I got octoprint working with this script on my old laptop but couldn't find any way to configure the integrated laptop cam as the webcam. How would I do that?

**Comment by paukstelis** [comment]
There isn't exactly an "easy" way to do this, because the script requires that you plug the camera in. One possible solution is to plug in some other USB device that has a serial number. Then you can modify either the service file or the udev rules to point to your integrated camera (probably /dev/video0)

**Comment by OscarCreator** [comment]
Okay, thanks for the help. I will try and see if I can get this to work.

**Comment by OscarCreator** [comment]
Wow, picam and the editing the device to /dev/video0 totally worked! 🥳
![Screenshot_20240514-173953~2.png](https://github.com/paukstelis/octoprint_deploy/assets/53407525/51c42f82-64ed-404a-9d46-13a2ee677eed)
