### ISSUE TITLE
Questions (not issue)

### ISSUE THREAD

**Issue by ravinder-Olivier** [paukstelis/octoprint_deploy#84]
Sorry if these are dumb questions, or have already been answered before, but I couldn't find any answers.
1. How does this work? It doesn't seem to use docker
2. How do I start it after a restart? Will it automatically restart?
3. How to install plugins to all of the instances? I also read somewhere about a template instance, does that have a place in this?

Thanks!

**Comment by paukstelis** [comment]
> Sorry if these are dumb questions, or have already been answered before, but I couldn't find any answers.
> 
> 1. How does this work? It doesn't seem to use docker
No, it does not use Docker. Docker adds way too many complications when coupled with hardware.  It starts multiple instances out of the same virtual environment. The video link from ERRF2022 provides the most in-depth explanation.
> 2. How do I start it after a restart? Will it automatically restart?
All instances and camera services will restart after a reboot.
> 3. How to install plugins to all of the instances? I also read somewhere about a template instance, does that have a place in this?
The template is simply what gets copied to make the new instances. This means if you have some specific configuration or files you want in your instances, you can include them in the template and they will become part of each new instance you make.
Because it is shared virtual environment, any plugin you install will be available to ALL the instances (once those instances are restarted). The configuration of those plugins is independent for each instance (unless they are configured in the template).
> 
> Thanks!
